In [2]:
import numpy as np
import pandas as pd

In [3]:
# Thông tin về dữ liệu
info = pd.read_csv("../ml-100k/u.info", header=None, sep="\t")
info.head()

                0
0       943 users
1      1682 items
2  100000 ratings

In [4]:
# Các loại occupation
occupation = pd.read_csv("../ml-100k/u.occupation", header=None, sep="\t")
print("Số lượng ngành nghề:")
print(len(occupation))
print("Các loại ngành nghề:")
print(occupation[0].tolist())

Số lượng ngành nghề:
21
Các loại ngành nghề:
['administrator', 'artist', 'doctor', 'educator', 'engineer', 'entertainment', 'executive', 'healthcare', 'homemaker', 'lawyer', 'librarian', 'marketing', 'none', 'other', 'programmer', 'retired', 'salesman', 'scientist', 'student', 'technician', 'writer']

In [5]:
# Các thể loại phim
genre = pd.read_csv("../ml-100k/u.genre", header=None, sep="\t")
print("Số lượng thể loại phim:")
print(len(genre))
print("Các thể loại phim:")
print(genre[0].tolist())

Số lượng thể loại phim:
19
Các thể loại phim:
['unknown|0', 'Action|1', 'Adventure|2', 'Animation|3', "Children's|4", 'Comedy|5', 'Crime|6', 'Documentary|7', 'Drama|8', 'Fantasy|9', 'Film-Noir|10', 'Horror|11', 'Musical|12', 'Mystery|13', 'Romance|14', 'Sci-Fi|15', 'Thriller|16', 'War|17', 'Western|18']

In [6]:
# Dữ liệu về người dùng
users = pd.read_csv("../ml-100k/u.user", header=None, sep="|")
users.columns = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [7]:
# Dữ liệu về phim
movies = pd.read_csv("../ml-100k/u.item", header=None, sep="|", encoding='latin-1')
movies.columns = ['movie_id', 'title', 'release_date', 'video_release_date', 'IMDb_URL'] + genre[0].tolist()
movies.head()

,movie_id,title,release_date,video_release_date,IMDb_URL,unknown|0,Action|1,Adventure|2,Animation|3,Children's|4,...,Fantasy|9,Film-Noir|10,Horror|11,Musical|12,Mystery|13,Romance|14,Sci-Fi|15,Thriller|16,War|17,Western|18
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [8]:
# Dữ liệu về Ratings
ratings = pd.read_csv("../ml-100k/u.data", header=None, sep="\t")
ratings.columns = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [9]:
# Gộp dữ liệu người dùng và ratings
user_ratings = pd.merge(ratings, users, on='user_id')
user_ratings.head()

   user_id  movie_id  rating  timestamp  age gender  occupation zip_code
0      196       242       3  881250949   49      M      writer    55105
1      186       302       3  891717742   39      F   executive    00000
2       22       377       1  878887116   25      M      writer    40206
3      244        51       2  880606923   28      M  technician    80525
4      166       346       1  886397596   47      M    educator    55113

In [10]:
# Top 10 phim được đánh giá cao nhất
top_movies = user_ratings.groupby('movie_id')['rating'].mean().sort_values(ascending=False).head(10)
top_movies = pd.merge(top_movies, movies[['movie_id', 'title']], on='movie_id')
print("Top 10 phim được đánh giá cao nhất:")
print(top_movies[['title', 'rating']])

Top 10 phim được đánh giá cao nhất:
                                               title  rating
0                                 Prefontaine (1997)     5.0
1                          Santa with Muscles (1996)     5.0
2         Marlene Dietrich: Shadow and Light (1996)      5.0
3                                    Star Kid (1997)     5.0
4  Entertaining Angels: The Dorothy Day Story (1996)     5.0
5                     They Made Me a Criminal (1939)     5.0
6                      Great Day in Harlem, A (1994)     5.0
7               Saint of Fort Washington, The (1993)     5.0
8                               Aiqing wansui (1994)     5.0
9                      Someone Else's America (1995)     5.0

In [ ]:
# Danh sách thể loại phim
genre_list = genre[0].tolist()

# Gộp dữ liệu ratings và movies
data_item = pd.merge(
    ratings[['user_id', 'movie_id', 'rating']],
    movies,
    on='movie_id'
 )

# Loại bỏ các cột không cần thiết
data_item.drop(
    columns=['user_id', 'movie_id', 'release_date', 'video_release_date', 'IMDb_URL'],
    inplace=True
 )

# Với mỗi thể loại, lấy top 3 phim theo rating trung bình
top_3_genre = pd.DataFrame()
for gen in genre_list:
    g_r = data_item[data_item[gen] == 1]
    new_gen = pd.DataFrame(
        g_r.groupby('title', as_index=False)['rating']
        .mean()
        .sort_values(['rating', 'title'], ascending=[False, True])
        .head(3)
    )
    new_gen.insert(0, 'genre', gen)
    top_3_genre = pd.concat([top_3_genre, new_gen], ignore_index=True)

top_3_genre

:

In [16]:
# Gộp dữ liệu ratings và users
data_user_og = pd.merge(ratings, users, on='user_id')
data_user_og.drop(columns=['user_id'], inplace=True)

# Gộp dữ liệu ratings, users và movies
data_user_item = pd.merge(data_user_og, movies, on='movie_id')
data_user_item.drop(columns=['movie_id', 'release_date', 'video_release_date', 'IMDb_URL'], inplace=True)
top_3_genre = pd.DataFrame()
for occ in occupation[0].tolist():
    o_r = data_user_item[data_user_item['occupation'] == occ]
    new_occ = pd.DataFrame(
        o_r.groupby('title', as_index=False)['rating']
        .mean()
        .sort_values(['rating', 'title'], ascending=[False, True])
        .head(3)
    )
    new_occ.insert(0, 'occupation', occ)
    top_3_genre = pd.concat([top_3_genre, new_occ], ignore_index=True)

top_3_genre

       occupation                                title  rating
0   administrator                A Chef in Love (1996)     5.0
1   administrator                     Aparajito (1956)     5.0
2   administrator               Assignment, The (1997)     5.0
3          artist                 39 Steps, The (1935)     5.0
4          artist  Adventures of Pinocchio, The (1996)     5.0
..            ...                                  ...     ...
58     technician               Assignment, The (1997)     5.0
59     technician                      Basquiat (1996)     5.0
60         writer                 Aiqing wansui (1994)     5.0
61         writer                        Caught (1996)     5.0
62         writer                     Dark City (1998)     5.0

[63 rows x 3 columns]

In [21]:
# Tạo cột nhóm tuổi
bins = [0, 6, 12, 18, 25, 35, 45, 50, 56, 100]
labels = ['0-5', '6-11', '12-17', '18-24', '25-34', '35-44', '45-49', '50-55', '56+']
users['age_group'] = pd.cut(users['age'], bins=bins, labels=labels, right=False)

# Gộp ratings với users để lấy thông tin nhóm tuổi
data_user_age = pd.merge(ratings, users, on='user_id')
data_user_age.drop(columns=['user_id'], inplace=True)

# Gộp tiếp với movies để lấy thông tin phim
data_user_item_age = pd.merge(data_user_age, movies, on='movie_id')
data_user_item_age.drop(columns=['movie_id', 'release_date', 'video_release_date', 'IMDb_URL'], inplace=True)

# Lấy top 3 phim theo rating trung bình cho từng nhóm tuổi
data_user_item_age_sorted = (
    data_user_item_age
    .groupby(['age_group', 'title'], as_index=False)['rating']
    .mean()
    .sort_values('rating', ascending=False)
 )

top_3_age = (
    data_user_item_age_sorted
    .groupby('age_group')
    .head(3)
    .sort_values(['age_group', 'title'], ascending=[True, True])
    .reset_index(drop=True)
 )

top_3_age

   age_group                                              title  rating
0       6-11                              101 Dalmatians (1996)     5.0
1       6-11                                   First Kid (1996)     5.0
2       6-11                                Forrest Gump (1994)     5.0
3      12-17                         Three Colors: White (1994)     5.0
4      12-17  Until the End of the World (Bis ans Ende der W...     5.0
5      12-17                                 Wild Things (1998)     5.0
6      18-24                                   Afterglow (1997)     5.0
7      18-24                             Beautiful Thing (1996)     5.0
8      18-24                                  Full Speed (1996)     5.0
9      25-34                               Critical Care (1997)     5.0
10     25-34                                   Crossfire (1947)     5.0
11     25-34  Entertaining Angels: The Dorothy Day Story (1996)     5.0
12     35-44                               Aiqing wansui (1994)     5.0
13     35-44                                        Anna (1996)     5.0
14     35-44                             Assignment, The (1997)     5.0
15     45-49                                   Aparajito (1956)     5.0
16     45-49                             Band Wagon, The (1953)     5.0
17     45-49                                 Bitter Moon (1992)     5.0
18     50-55                         Smile Like Yours, A (1997)     5.0
19     50-55              Visitors, The (Visiteurs, Les) (1993)     5.0
20     50-55                                  Wonderland (1997)     5.0
21       56+                             Shall We Dance? (1996)     5.0
22       56+                           Some Mother's Son (1996)     5.0
23       56+                         Weekend at Bernie's (1989)     5.0